keywords:
  
  - partnered with
  - signed an MoU with
  - entered into agreement with
  - strategic partnership with  
  - joint venture with
  - collaboration with
  - alliance with
  - co-develop with

  - commissioned a 
  - awarded EPC contract to 
  - project awarded to
  - project developed by
  - project executed by
  - project implemented by
  - plant commissioned by
  - installation completed by