feeds:
  - "https://www.google.com/alerts/feeds/08351022796024786384/14837196326529313263"
  - "https://www.google.com/alerts/feeds/08351022796024786384/14837196326529312265"
  - "https://www.google.com/alerts/feeds/08351022796024786384/14837196326529310998"
  - "https://www.google.com/alerts/feeds/08351022796024786384/18350939668444752677"